name: CI on any branch master created

on:
  release:
    types: [published]
    tags:
      - c1*
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.events.ref == 'refs/tags/c10'
    steps:
      - name: Build
        run: |
          echo "Tag is a match"
