name: CI on any branch only created

on:
  create:
    branches:
      - master
    tags:
      - v1*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
