name: CI on any branch master created

on:
  release:
    types: [published]
    tags:
      - c1*
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        if: contains(github.ref, "release")
        run: |
          echo "Tag is a match"
