name: CI on any branch master created

on:
  release:
    types: [created]
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Build
        run: |
          echo "Tag is a match master"
