name: CI on any branch master created

on:
  push: 
    branches: 
      - refs/tags/*
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
