name: CI on any branch master created

on:
  release:
    types: [published]
    tags:
      - c1*
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    if: $GITHUB_RE
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world! $GITHUB_REF
