name: CI on just another branch

on:
  push:
    branches:
      - anyBranch
    tags:
      - c1*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
